const {chromium}=require('playwright');
const path=require('path');
const {pathToFileURL}=require('url');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--allow-file-access-from-files']});
 const page=await browser.newPage({viewport:{width:1280,height:720}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.calls=[];window.Marlico={refresh(){},connect(){window.calls.push('connect')},stop(){window.calls.push('stop')},importEnv(){window.calls.push('importEnv')},battery(){window.calls.push('battery')},save(v){window.calls.push('save')},wake(){window.calls.push('wake')},monitor(){window.calls.push('monitor')},processes(){window.calls.push('processes')},inventory(){window.calls.push('inventory')},screen(){window.calls.push('screen')}};});
 await page.goto(pathToFileURL(path.resolve(__dirname,'../assets/index.html')).href);
 const base={configured:true,hasToken:true,displayName:'Alex',users:'1234567890',mac:'02:11:22:33:44:55',pcIp:'192.168.1.50',broadcast:'255.255.255.255',port:9,autoStart:true,state:'online',running:true,network:'Cabo conectado',botName:'MeuBot',events:[{kind:'good',text:'Sinal para ligar o PC enviado · Telegram',time:Date.now()},{kind:'good',text:'Telegram conectado. Pronto para receber comandos.',time:Date.now()-300000},{kind:'info',text:'Configurações atualizadas.',time:Date.now()-360000}]};
 const dir=path.resolve(__dirname,'../../dist');fs.mkdirSync(dir,{recursive:true});
 for(const size of [[1280,720],[960,540],[1920,1080]]){
  await page.setViewportSize({width:size[0],height:size[1]});await page.evaluate(s=>window.renderState(s),base);
  await page.screenshot({path:path.join(dir,`interface-${size[0]}.png`)});
  const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,height:innerHeight,scrollH:document.documentElement.scrollHeight}));
  if(metrics.scroll>metrics.width)throw Error('Horizontal overflow '+JSON.stringify(metrics));
  if(metrics.scrollH>metrics.height)throw Error('Dashboard exceeds the TV screen '+JSON.stringify(metrics));
  console.log('Layout',size.join('x'),JSON.stringify(metrics));
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(s=>window.renderState(s),base);
 const phone=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));if(phone.scroll>phone.width)throw Error('Phone layout has horizontal overflow '+JSON.stringify(phone));
 await page.setViewportSize({width:1280,height:720});
 await page.locator('#main-action').click();await page.locator('#main-action').click();
 if(await page.evaluate(()=>window.calls.filter(x=>x==='wake').length)!==1)throw Error('Wake duplicate guard failed');
 await page.locator('[data-panel="settings"]').click();await page.screenshot({path:path.join(dir,'interface-settings.png')});
 if(await page.locator('#token').inputValue()!=='')throw Error('Saved token exposed');
 await page.locator('#import-button').click();if(!await page.evaluate(()=>window.calls.includes('importEnv')))throw Error('Import bridge not called');
 await page.locator('#import-button').focus();await page.keyboard.press('ArrowDown');
 if(await page.evaluate(()=>document.activeElement.id)!=='token')throw Error('Dpad form focus failed');
 await page.keyboard.press('Escape');if(!await page.locator('#overlay').isHidden())throw Error('Back navigation failed');
 await page.evaluate(s=>window.renderState({...s,state:'error',running:false,detail:'Outra cópia está usando este bot. Pare o bot no Termux e no PC; depois toque em Conectar.'}),base);
 await page.screenshot({path:path.join(dir,'interface-error.png')});
 if(!(await page.locator('#hero-description').innerText()).includes('Outra cópia'))throw Error('Conflict guidance missing');
 await page.evaluate(s=>window.renderState({...s,configured:false,hasToken:false,state:'off',running:false,events:[]}),base);
 await page.screenshot({path:path.join(dir,'interface-setup.png')});
 await page.locator('#main-action').click();if(!await page.locator('#settings-panel').isVisible())throw Error('First setup failed');await page.waitForFunction(()=>document.activeElement.id==='import-button');
 await page.locator('#auto-start').focus();const checked=await page.locator('#auto-start').isChecked();await page.keyboard.press('Enter');
 if(await page.locator('#auto-start').isChecked()===checked)throw Error('Remote OK did not toggle autostart');
 await page.keyboard.press('Escape');await page.setViewportSize({width:960,height:540});
 await page.evaluate(s=>window.renderState({...s,events:Array.from({length:30},(_,i)=>({kind:'info',text:'Evento '+i,time:Date.now()}))}),base);
 await page.locator('nav [data-panel="monitor"]').click();await page.waitForFunction(()=>document.activeElement.id==='refresh-monitor');
 if(!await page.locator('#monitor-panel').isVisible())throw Error('PC monitor panel did not open');
 const monitorSize=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));if(monitorSize.scroll>monitorSize.width)throw Error('Phone monitor has horizontal overflow '+JSON.stringify(monitorSize));
 await page.screenshot({path:path.join(dir,'interface-monitor.png')});
 await page.evaluate(()=>window.pcStatus({cpuPercent:18,memoryUsedBytes:1024,memoryTotalBytes:2048,diskUsedBytes:1024,diskTotalBytes:4096,uptimeSeconds:3600,activeWindow:'Desktop'}));
 if(await page.locator('#m-cpu').innerText()!=='18%')throw Error('PC metrics were not rendered');
 await page.locator('#refresh-inventory').click();if(!await page.evaluate(()=>window.calls.includes('inventory')))throw Error('Inventory bridge missing');await page.evaluate(()=>window.pcInventory({fields:{'Sistema operacional':'Windows 11'},installedPrograms:[{name:'Exemplo',version:'1.0'}]}));if(!(await page.locator('#monitor-inventory').innerText()).includes('Windows 11'))throw Error('Hardware inventory was not rendered');
 await page.locator('#capture-screen').click();if(!await page.evaluate(()=>window.calls.includes('screen')))throw Error('Screen request bridge missing');
 await page.keyboard.press('Escape');
 await page.locator('nav [data-panel="activity"]').click();await page.waitForFunction(()=>document.activeElement.id==='close-panel');await page.keyboard.press('ArrowDown');
 await page.waitForFunction(()=>document.querySelector('#activity-panel').scrollTop>0);
 await page.keyboard.press('Escape');await page.locator('[data-panel="help"]').click();await page.waitForFunction(()=>document.activeElement.id==='close-panel');await page.keyboard.press('ArrowDown');
 await page.waitForFunction(()=>document.querySelector('#help-panel').scrollTop>0);
 if(errors.length)throw Error(errors.join('\n'));
 console.log('OK: rendering, D-pad, navigation, import, no token exposure, and duplicate-click guard.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
